name: Build
run-name: Build application
on: [push]

jobs:
  Build-Go:
    name: Build Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Build
        run: go build -o ./build/dosetti cmd/dosetti/main.go
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build/dosetti
